
dockerRegistry:
  enabled: ${providers.dockerRegistry.enabled:false}
  accounts:
    - name: ${providers.dockerRegistry.primaryCredentials.name}
      address: ${providers.dockerRegistry.primaryCredentials.address}
      username: ${providers.dockerRegistry.primaryCredentials.username:}
      passwordFile: ${providers.dockerRegistry.primaryCredentials.passwordFile}
      repositories:
         - library/nginx
         - willgorman/graphite
         - willgorman/nginx-test
